- name: Pull and Push Ubuntu 24.04
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    image_name: ubuntu
    image_tag: "24.04"
    dockerhub_repo: "{{ lookup('env', 'DOCKERHUB_USER') }}"
    build_tag: "{{ lookup('env', 'IMAGE_TAG') }}"

  pre_tasks:
    - name: Validate required environment variables
      ansible.builtin.fail:
        msg: "Required environment variable '{{ item.name }}' is not set or empty"
      when: item.value == ""
      loop:
        - { name: "DOCKERHUB_USER", value: "{{ dockerhub_repo }}" }
        - { name: "IMAGE_TAG",      value: "{{ build_tag }}" }

  tasks:
    - name: Log in to Docker Hub
      community.docker.docker_login:
        username: "{{ lookup('env', 'DOCKERHUB_USER') }}"
        password: "{{ lookup('env', 'DOCKERHUB_PASS') }}"

    - name: Pull Ubuntu 24.04
      community.docker.docker_image:
        name: "{{ image_name }}"
        tag: "{{ image_tag }}"
        source: pull

    - name: Debug tagging info
      ansible.builtin.debug:
        msg: "Tagging {{ image_name }}:{{ image_tag }} as {{ dockerhub_repo }}/{{ image_name }}:{{ build_tag }}"

    - name: Tag and Push Ubuntu image to Docker Hub
      community.docker.docker_image:
        name: "{{ image_name }}:{{ image_tag }}"
        repository: "{{ dockerhub_repo }}/{{ image_name }}"
        tag: "{{ build_tag }}"
        source: local
        push: true

    - name: Generate Trivy CSV Reports
      community.docker.docker_container:
        name: "trivy_scan_{{ item | lower }}"
        image: aquasec/trivy
        state: started
        # On met auto_remove à false pour éviter l'erreur Ansible
        auto_remove: false
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - "{{ lookup('env', 'PWD') }}:/reports"
        command: >
          image --format csv
          --output /reports/trivy_{{ item | lower }}.csv
          --severity {{ item }}
          {{ dockerhub_repo }}/{{ image_name }}:{{ build_tag }}
        detach: false
      loop:
        - CRITICAL
        - MEDIUM
        - LOW
      # On ignore les erreurs ici pour que le pipeline continue même si Trivy trouve des failles
      ignore_errors: true

    - name: Cleanup Trivy containers
      community.docker.docker_container:
        name: "trivy_scan_{{ item | lower }}"
        state: absent
      loop:
        - CRITICAL
        - MEDIUM
        - LOW

    - name: List generated reports
      ansible.builtin.shell: ls -lh trivy_*.csv
      register: ls_output
      ignore_errors: true

    - name: Show reports created
      ansible.builtin.debug:
        msg: "{{ ls_output.stdout_lines | default('Aucun fichier CSV trouvé') }}"

    - name: Log out from Docker Hub
      community.docker.docker_login:
        state: absent
