- name: Pull, Push and Scan Ubuntu
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    image_name: ubuntu
    image_tag: "24.04"
    dockerhub_repo: "{{ lookup('env', 'DOCKERHUB_USER') }}"
    build_tag: "{{ lookup('env', 'IMAGE_TAG') }}"

  tasks:
    - name: Log in to Docker Hub
      community.docker.docker_login:
        username: "{{ lookup('env', 'DOCKERHUB_USER') }}"
        password: "{{ lookup('env', 'DOCKERHUB_PASS') }}"

    - name: Build and Push Docker image
      community.docker.docker_image:
        name: "{{ dockerhub_repo }}/{{ image_name }}"
        tag: "{{ build_tag }}"
        build:
          path: .
          pull: true
        source: build
        push: true

    - name: Generate Trivy CSV Reports
      community.docker.docker_container:
        name: "trivy_scan_{{ item | lower }}"
        image: aquasec/trivy
        state: started
        auto_remove: false
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        # On scan l'image locale qui vient d'être tagguée
        command: "image --quiet --format template --template @/contrib/csv.tpl --severity {{ item }} {{ dockerhub_repo }}/{{ image_name }}:{{ build_tag }}"
        detach: false
      loop:
        - CRITICAL
        - MEDIUM
        - LOW
      register: scan_results

    - name: Save reports to files
      ansible.builtin.copy:
        content: "{{ item.container.Output }}"
        dest: "./trivy_{{ item.item | lower }}.csv"
      loop: "{{ scan_results.results }}"
      when: item.container is defined

    - name: Cleanup Trivy containers
      community.docker.docker_container:
        name: "trivy_scan_{{ item | lower }}"
        state: absent
      loop:
        - CRITICAL
        - MEDIUM
        - LOW

    - name: Log out from Docker Hub
      community.docker.docker_login:
        state: absent